apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: llama-stack-3scale-example6
  janus-idp.io/tekton: llama-stack-3scale-example6
  backstage.io/kubernetes-id: llama-stack-3scale-example6
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: llama-stack-3scale-example6
resources:
  - application-dev.yaml