apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: llama-stack-3scale-example6-gitops
  description: This is GitOps manifest for llama-stack-3scale-example6   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=llama-stack-3scale-example6
    janus-idp.io/tekton: llama-stack-3scale-example6 
    backstage.io/kubernetes-id: llama-stack-3scale-example6 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/tpetkos 
  lifecycle: experimental  
