apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-llama-stack-3scale-example6-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-llama-stack-3scale-example6-gitops
    spec:
      serviceAccountName: llama-stack-3scale-example6-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=llama-stack-3scale-example6-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/llama-stack-3scale-example6-notebook -- git clone https://github.com/fpetk-rolling-demo/llama-stack-3scale-example6
      restartPolicy: Never
