apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: llama-stack-3scale-example6
  janus-idp.io/tekton: llama-stack-3scale-example6
  backstage.io/kubernetes-id: llama-stack-3scale-example6
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: llama-stack-3scale-example6
resources:
  - initialize-namespace/
  - llama-stack-deployment.yaml
  - pvc.yaml
  - service.yaml
  - route.yaml
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: run-config
    files:
      - config.yaml=llama-stack-run.yaml