apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: llama-stack-3scale-example6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: llama-stack-3scale-example6
  name: llama-stack-3scale-example6
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi