apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: llama-stack-3scale-example6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: llama-stack-3scale-example6
  name: llama-stack-3scale-example6
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: llama-stack-3scale-example6
    weight: 100
  wildcardPolicy: None
